### ISSUE TITLE
Cannot build fixes-combined branch

### ISSUE THREAD

**Issue by mickaelistria** [jikespg/jikespg#2]
On latest Fedora release, build of the `fixes-combined` branch fails
```
mistria@localhost:~/git/jikespg/src$ make
gcc -c ctabs.c
gcc -c globals.c
jikespg jikespg
make: jikespg: No such file or directory
make: *** [Makefile:14: lpgact.i] Error 127
```

**Comment by stephan-herrmann** [comment]
Thanks for reporting.

First answers from https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1520#issuecomment-1803753553:

Interesting. Here jikespg tries to bootstrap its own grammar parser.

(On bootstrapping see the corresponding section in jikespg.htm)

Two options:
* install a pre-built jikespg from your distro (Ubuntu has one that works well enough, don't know about other distros).
* simply touch file lpgact.i to avoid triggering that make rule

I never encountered that situation but we should definitely document this ...

**Comment by mickaelistria** [comment]
> simply touch file lpgact.i to avoid triggering that make rule

Then can't we just remove this rule?

**Comment by stephan-herrmann** [comment]
> Then can't we just remove this rule?

I changed the trigger from comparison of file times to an explicit goal `bootstrap`.
